### ISSUE TITLE
Add per-fixture request information

### ISSUE THREAD

**Issue by twolfson** [underdogio/httpretty-fixtures#1]
While global request information works, it is not the best for tests (e.g. constantly shifting numbers). We should consider adding in support for per-fixture request information.

This would occur by wrapping `contextual_fixture` further to save any inbound requests to our instance under the fixture's key. Then, in the test we can return (non-decorator)/pass in as an argument (decorator) our server instance. When we use a method to access a fixture (e.g. `get_fixture`) from our server, then we can have things like `first_request`/`last_request`/`requests` on the fixture for a very nice experience.

``` python
class TestHttprettyFixtures(TestCase):
    @FakeServer.run(['hello'])
    def test_request(self, fake_server):
        fake_server.get_fixture('hello').first_request
        fake_server.get_fixture('hello').last_request
        fake_server.get_fixture('hello').requests
```

**Comment by brettlangdon** [comment]
This was resolved with #4
